try building manually with labels (#8)
* try building manually with labels
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

diff --git a/.github/workflows/build-deploy.yaml b/.github/workflows/build-deploy.yaml
--- a/.github/workflows/build-deploy.yaml
+++ b/.github/workflows/build-deploy.yaml
@@ -10,13 +10,14 @@ jobs:
       fail-fast: false
       matrix:
                     # tag           dockerfile in docker/     platforms
-        dockerfile: [[ubuntu-18.04, Dockerfile.ubuntu-18.04, 'linux/amd64,linux/ppc64le,linux/arm64'],
-                     [ubuntu-20.04, Dockerfile.ubuntu-20.04, 'linux/amd64,linux/ppc64le,linux/arm64'],
-                     [centos-7, Dockerfile.centos-7, 'linux/amd64,linux/ppc64le,linux/arm64'],
-                     [centos-8, Dockerfile.centos-8, 'linux/amd64,linux/ppc64le,linux/arm64'],
-                     [fedora, Dockerfile.fedora, 'linux/amd64,linux/ppc64le,linux/arm64']] # linux/ppc64le can fail
+        dockerfile: [[ubuntu-18.04, Dockerfile.ubuntu-18.04],
+                     [ubuntu-20.04, Dockerfile.ubuntu-20.04],
+                     [centos-7, Dockerfile.centos-7],
+                     [centos-8, Dockerfile.centos-8],
+                     [fedora, Dockerfile.fedora]] # linux/ppc64le can fail
+        arch: ['linux/amd64','linux/ppc64le','linux/arm64']
 
-    name: Build ${{ matrix.dockerfile[0] }}
+    name: Build ${{ matrix.dockerfile[0] }} ${{ matrix.arch }}"
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -34,6 +35,9 @@ jobs:
               exit 1;
           fi
 
+      - name: Pull Docker Layers
+        run: docker pull ghcr.io/buildsi/${{ env.container }} || exit 0 
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
 
@@ -47,14 +51,14 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build ${{ matrix.dockerfile[1] }}
+      - name: Build ${{ matrix.dockerfile[1] }} ${{ matrix.arch }}
         uses: docker/build-push-action@v2
         with:
           file: docker/${{matrix.dockerfile[1]}}
+          platforms: ${{ matrix.arch }}
           context: .
           load: true
-          tags: |
-            ghcr.io/buildsi/${{ env.container }}
+          tags: ghcr.io/buildsi/${{ env.container }}
 
       - name: Derive Compiler Labels
         id: labels
@@ -64,12 +68,13 @@ jobs:
           labels="--label compilers=\"${labels}\""
           printf "Saving compiler labels ${labels}\n"         
           echo "compiler_labels=${labels}" >> $GITHUB_ENV
-            
-      - name: Build & Deploy ${{ matrix.dockerfile[1] }}
+      
+      - name: Deploy ${{ matrix.dockerfile[1] }}
         uses: docker/build-push-action@v2
         with:
           file: docker/${{matrix.dockerfile[1]}}
-          platforms: ${{ matrix.dockerfile[2] }}
+          platforms: ${{ matrix.arch }}
+          context: .
           push: ${{ github.event_name != 'pull_request' }}
-          labels: ${{ steps.labels.outputs.compiler_labels }}
           tags: ghcr.io/buildsi/${{ env.container }}
+          labels: ${{ steps.labels.outputs.compiler_labels }}
